### ISSUE TITLE
Progress tracker

### ISSUE THREAD

**Issue by Vikctar** [devTimmy/E-Learning-Pad#6]
Lecturer needs to know how many students have viewed course work be it a video or a document. 
As such, lesson / unit material should be arranged in a chronological order. After a student has viewed a course content, it is marked as complete. This will help keep a track of course, completion progress.

**Comment by tmacharia** [comment]
# **Solution Approach**

If we are going to track viewership/readership of coursework/content uploaded by a lecturer in a particular unit and maintain visibility of current progress by both parties, the following points will tackle the approach i came up with to solve this problem.
**N.B** _the terms **CourseWork** and **Content** shall be used interchangeably below._

## Student

- [x] On initial opening of a content by student, it should initialiaze a progress tracker with the following parameters being sent from the view. (StudentId, ContentId, Overall length of content, and CurrentProgress being 0.)
- [x] When the user exits that content page or tries navigating to another page., it calls the API with the following parameters to update coursework progress (ProgressId, CurrentProgress). If the updated current progress point matches the overall value required, coursework progress is marked as completed.

- [x] On the right side of the content, a student can view overall percentage progress for a particular coursework.

## Lecturer

- [ ] Lecturer can view/track students progress on a certain coursework.

- [ ] Lecturer can view/track coursework consumption progress for their students.

- [ ] Lecturer can view/track overall coursework consumption progress for an entire unit that they teach.

- [ ] Lecturer can view/track overall coursework consumption progress for all the units that they are in charge of.

**Comment by Vikctar** [comment]
I think you have all the key points captured. :+1: 
Now lets see it in action.
